// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolPortalAPI.Data;

#nullable disable

namespace SchoolPortalAPI.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260213143359_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolPortalAPI.Models.Calender", b =>
                {
                    b.Property<long>("Eventid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Eventid"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Eventid");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Class", b =>
                {
                    b.Property<long>("Classid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Classid"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Classid");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.ClassCourse", b =>
                {
                    b.Property<long>("Classcourseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Classcourseid"));

                    b.Property<long>("Courseid")
                        .HasColumnType("bigint");

                    b.HasKey("Classcourseid");

                    b.ToTable("ClassCourses");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Course", b =>
                {
                    b.Property<long>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Courseid"));

                    b.Property<long?>("Classid")
                        .HasColumnType("bigint");

                    b.Property<string>("Classtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Finalexamdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Teacherid")
                        .HasColumnType("bigint");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Courseid");

                    b.HasIndex("Classid");

                    b.HasIndex("Teacherid");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Equipment", b =>
                {
                    b.Property<long>("Equipmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Equipmentid"));

                    b.Property<string>("Eqcatry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eqcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Equipmentid");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Exam", b =>
                {
                    b.Property<long>("Examid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Examid"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<long?>("Classid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Courseid")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Enddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PossibleScore")
                        .HasColumnType("int");

                    b.Property<string>("Startdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Starttime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Examid");

                    b.HasIndex("Classid");

                    b.HasIndex("Courseid");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.ExamStuTeach", b =>
                {
                    b.Property<long>("Estid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Estid"));

                    b.Property<string>("Answerimage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Courseid")
                        .HasColumnType("bigint");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Examid")
                        .HasColumnType("bigint");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<long?>("Studentid")
                        .HasColumnType("bigint");

                    b.Property<long>("Teacherid")
                        .HasColumnType("bigint");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Estid");

                    b.HasIndex("Courseid");

                    b.HasIndex("Examid");

                    b.HasIndex("Studentid");

                    b.HasIndex("Teacherid");

                    b.ToTable("ExamStuTeaches");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Exercise", b =>
                {
                    b.Property<long>("Exerciseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Exerciseid"));

                    b.Property<long?>("Classid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Courseid")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enddate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endtime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Score")
                        .HasColumnType("bigint");

                    b.Property<string>("Startdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Starttime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Exerciseid");

                    b.HasIndex("Classid");

                    b.HasIndex("Courseid");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.ExerciseStuTeach", b =>
                {
                    b.Property<long>("Exstid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Exstid"));

                    b.Property<string>("Answerimage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Courseid")
                        .HasColumnType("bigint");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Exerciseid")
                        .HasColumnType("bigint");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<long?>("Studentid")
                        .HasColumnType("bigint");

                    b.Property<long>("Teacherid")
                        .HasColumnType("bigint");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Exstid");

                    b.ToTable("ExerciseStuTeaches");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Manager", b =>
                {
                    b.Property<long>("Assistantid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Assistantid"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Userid")
                        .HasColumnType("bigint");

                    b.HasKey("Assistantid");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.News", b =>
                {
                    b.Property<long>("Newsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Newsid"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enddate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Startdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Newsid");

                    b.ToTable("News");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RelatedId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelatedType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("Classid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Courseid")
                        .HasColumnType("bigint");

                    b.Property<long>("ScoreValue")
                        .HasColumnType("bigint");

                    b.Property<string>("Score_month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StuCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StuCode");

                    b.Property<long?>("Studentid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Classid");

                    b.HasIndex("Courseid");

                    b.HasIndex("Studentid");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Student", b =>
                {
                    b.Property<long>("Studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Studentid"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birthdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Classeid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Debt")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentNum1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentNum2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registerdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Score_month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StuCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("Studentid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Teacher", b =>
                {
                    b.Property<long>("Teacherid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Teacherid"));

                    b.Property<long?>("Courseid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Userid")
                        .HasColumnType("bigint");

                    b.HasKey("Teacherid");

                    b.HasIndex("Userid");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.User", b =>
                {
                    b.Property<long>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Userid"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Userid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Course", b =>
                {
                    b.HasOne("SchoolPortalAPI.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("Classid");

                    b.HasOne("SchoolPortalAPI.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("Teacherid");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Exam", b =>
                {
                    b.HasOne("SchoolPortalAPI.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("Classid");

                    b.HasOne("SchoolPortalAPI.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Courseid");

                    b.Navigation("Class");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.ExamStuTeach", b =>
                {
                    b.HasOne("SchoolPortalAPI.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolPortalAPI.Models.Exam", "Exam")
                        .WithMany("ExamStuTeachs")
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolPortalAPI.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Studentid");

                    b.HasOne("SchoolPortalAPI.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Exam");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Exercise", b =>
                {
                    b.HasOne("SchoolPortalAPI.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("Classid");

                    b.HasOne("SchoolPortalAPI.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Courseid");

                    b.Navigation("Class");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Score", b =>
                {
                    b.HasOne("SchoolPortalAPI.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("Classid");

                    b.HasOne("SchoolPortalAPI.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Courseid");

                    b.HasOne("SchoolPortalAPI.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Studentid");

                    b.Navigation("Class");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Teacher", b =>
                {
                    b.HasOne("SchoolPortalAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Exam", b =>
                {
                    b.Navigation("ExamStuTeachs");
                });

            modelBuilder.Entity("SchoolPortalAPI.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
